### ISSUE TITLE
load first world, immediate crash Version 1.0.15

### ISSUE THREAD

**Issue by TsmckdTheCLaP** [Sunekaer/stoneBlock#158]
The game crashed whilst exception in server tick loop
Error: java.lang.NoClassDefFoundError: scala/reflect/io/Path

this is the error that pops up, upon crash

im playing singlplayer and on an edited version of the modpack, any ideas as to whats goin on with the pack? fully updated drivers gtx 970TI strix 4GB and 64 GB ram

**Comment by TsmckdTheCLaP** [comment]
does not work on version 1.0.16 either

**Comment by Koyoss** [comment]
Delete scala-reflect in minecraft/install/libraries/org/scala-lang/scala-reflect/2.11.1

I had the same issue and it fixed it.

**Comment by TsmckdTheCLaP** [comment]
> Delete scala-reflect in minecraft/install/libraries/org/scala-lang/scala-reflect/2.11.1
> 
> I had the same issue and it fixed it.

allright gimme a sec to relaunch now
